controller_manager:
  ros__parameters:
    update_rate: 100

    joint_effort_controller:
      type: effort_controllers/JointGroupEffortController
  
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_effort_controller:
  ros__parameters:
    joints:
      - revolute1
      - revolute2
      - revolute3
      - revolute4
      - revolute5
      - revolute6
    interface_name: effort
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity